function [ext_forces_b, ext_torques_b] = external_stimuli(...
  cmd_motor_speeds,...
  k_force,...
  k_torque,...
  arm_lengths...
)
  ext_forces_b = zeros(3, 1);
  u_motor_sq = cmd_motor_speeds.*cmd_motor_speeds;
  ext_forces_b(3) = k_force*sum(u_motor_sq);
  
  ext_torques_b = zeros(3, 1);
  ext_torques_b(1) = arm_lengths(2)*k_force*u_motor_sq(2) - ...
    arm_lengths(4)*k_force*u_motor_sq(4);
  ext_torques_b(2) = arm_lengths(3)*k_force*u_motor_sq(3) - ...
    arm_lengths(1)*k_force*u_motor_sq(1);
  ext_torques_b(3) = k_torque*(...
    -u_motor_sq(1) + u_motor_sq(2) - u_motor_sq(3) + u_motor_sq(4)...
  );
endfunction